### ISSUE TITLE
Not working on Windows with dedicated GPU

### ISSUE THREAD

**Issue by AnsgarTOdinson** [dvlden/ultrawideo#46]
### Describe the bug
Upscale has stopped functioning at all.  What's more, stretch does work but once stretched the image stays stretched no matter what other modes I cycle through.  This persists until the extension is set to normal, then closed and re opened. 

### Reproduction steps
Cycle through the modes while watching a full screen video

### Expected behavior
I would expect upscale to crop and zoom the video as it once did, stretch to work as it is now and when switching back to normal, the video to return to normal without having to exit the browser.

### Environment
- **OS**: Windows 10 build 19041.746
- **Browser**: Chrome Version 88.0.4324.104 (Official Build) (64-bit)

**Comment by dvlden** [comment]
Can some Windows + Chrome users confirm this? 
I just checked on YouTube and it works as expected. 

Can you also tell me is this some platform specific issue @AnsgarTOdinson ?

**Comment by brusli009** [comment]
Got the same bug and it started happeing today

**Comment by dvlden** [comment]
@brusli009 Please tell me your OS, Browser and which Platform specifically?

Tested again today, no issues on my end:

### Environment

- OS: macOS Big Sur v11.1
- Browser: Google Chrome v88.0.4324.96

**Comment by dvlden** [comment]
Downloading Windows 10 to run on Parallels Desktop.

**Comment by brusli009** [comment]
I got it on Win 10 buil 18363 with chrome on v88.0.4324.104 on youtube and netflix

**Comment by jcracken** [comment]
I can confirm similar behavior on Win10 20H2 using Edge 88.0.705.50 on YouTube. However, I only have just installed this extension--another extension I was using, UltraWide Video, recently prompted a behavior of stretching the video when set to crop mode on YouTube. It does not appear to be in the Chrome Store anymore, so I installed this extension to replace it. There may be a common issue between the two extensions or it may be a coincidence.

**Comment by SplayedAsterisk** [comment]
Confirming similar behavior starting today with windows 10 and chrome.  upscale now seems to have the same effect as stretch. used on a 21:9 video source (prime video and disney+) it gives me a distorted image that hits the sides of the screen but does not reach the top or bottom.  i can cycle through all the modes and get back to normal while in full screen, but where upscale used to fill the monitor with those same sources, now it only stretches them.

**Comment by AnsgarTOdinson** [comment]
Prime video and Disney+ for me as well.

**Comment by dvlden** [comment]
Thank you all for reporting this problem and for your involvement to help. 
I installed Parallels Desktop and Windows 10 yesterday and been testing the extension on it. 

I can only confirm the issue #43, which affects all Windows users. But unfortunately, I'm unable to reproduce this problem where any of the modes do not behave as they should.

I'll try to improve the keystrokes issue and will keep testing the Stretch/Upscale on various platforms. 

@AnsgarTOdinson I don't know if Chrome and Graphic card could have something in common to make this issue, but let me know if you experience this problem again?

**Comment by jcracken** [comment]
Hi,

I did some searching around and someone pointed out that disabling hardware
acceleration in Chrome settings fixed the issue. So it may be hardware
related.

I'm using an RTX 2070 as my graphics card.

Rohin Galhotra

**Comment by dvlden** [comment]
Ouch. I am running Intel graphics, so... xD
I'll ask some friends around to allow me to test it via Screen Sharing software, just to make sure it's hardware related issue. 

Thanks a lot for this research, it is very helpful! @jcracken

**Comment by Smart123s** [comment]
After some testing I've got the following results:

**NOT Working:
OS: Windows 10
Browser: Chrome
GPU: Nvidia GTX 1650 Super**

Working:
OS: Windows 10
Browser: Chrome
GPU: Intel HD Graphics 4600

Working:
OS: Ubuntu 20.10
Browser: Chrome
GPU: Nvidia GTX 1650 Super

Working:
OS: Windows 10
Browser: Firefox (Nightly)
GPU: Nvidia GTX 1650 Super

So I don't think that this issue is related to the extension.

**Comment by dvlden** [comment]
So the conclusion from @Smart123s and @jcracken research is that it has to be a Chrome release issue, affected by the graphic card?

**Comment by brusli009** [comment]
It is now fixed on my pc after disabling hardware acceleration in chrome

**Comment by SplayedAsterisk** [comment]
ok, thanks everyone! also fixed for me after disabling hardware acceleration in chrome.  i'm running a 2070 max-q and it seems like this may have started right after my most recent nvidia driver update.

**Comment by tamius-han** [comment]
There's a sorta better solution than the "disable hardware acceleration" workaround, because disabling hardware acceleration is — depending on your hardware — a bad solution (as it may result in frame dropping). 

* Don't zoom in the video all the way. Leave 5-10px wide black border at the sides. 

If you're using `transform: scale()` CSS property, this is trivial-ish. If you're using object-fit, you should be able to throw a `transform: scale(0.995)` or something on the video tag.

Standard disclaimers:
* this worked for me
* this may not work for me
* full disclosure: I do work on a similar extension

**Comment by AnsgarTOdinson** [comment]
Thanks, Ill give that a try as it has gone back to doing the same thing on my machine.

**Comment by markey** [comment]
@dvlden Could you provide this is as a patch to the source code? Just pointing me to the right file and line would suffice too. 
(I failed at monkey-patching it with Dev Tools).

PS: I'd like to add that with Edge (Dev Channel) on a 34" Ultrawide Monitor, *only* Youtube is affected by the issue. Netflix and Prime working fine.

**Comment by dvlden** [comment]
Hello @markey ,

I made a new branch with this patch that might possibly have an effect on this issue. Hopefully positive.
You can clone/download the branch and load the extension through developer mode.

If you are interested in this specific file and where would you put this line of CSS, you can find it here:
[gc-patch inject.scss](https://github.com/dvlden/ultrawideo/blob/gc-patch/src/styles/inject.scss#L34)

Make sure, if you plan to run this as developer - build the extension first and load everything unpacked from `dist` directory: `npm i & npm run build`

**Comment by jcracken** [comment]
Hey, I wanted to step in and say I no longer have this issue as of at least today (I tried a few days ago and the problem was still there, and now it's not).

I did install a new Nvidia driver recently, so it may have been fixed on their end.

Windows 10
Edge 89.0.774.54
Nvidia Driver 461.92

**Comment by Smart123s** [comment]
I've also tested it on https://archive.org and it does the exact same thing that it does on YouTube: `upscale` mode starches the video.
Updating my driver to 461.92 also didn't solve the problem.

Video: https://archive.org/details/SF143
Brave | 1.21.77 Chromium: 89.0.4389.90

**Comment by SendNukez** [comment]
I got the same Issue,

OS: `Win 10 (10.0.19042 Build 19042)`
Browser: `Chrome 89.0.4389.90`
GPU: `RTX 2070 (Driver 461.92)`

I've tried the new Branch (gc-patch) but no Luck, I've got the same Problem with my old UW Extension [UltraWide Video](https://chrome.google.com/webstore/detail/lngfncacljheahfpahadgipefkbagpdl) where it also only stretches and doesn't crop properly. I've tested on YT and the [archive.org](https://archive.org/details/SF143) Video @Smart123s mentioned.

Also tested on `Edge 89.0.774.63` and `Edge Beta 90.0.818.14`, same Issue.

**Comment by dvlden** [comment]
Thank you all for reporting in again. 
It's unfortunate that patch is not working as I expected it to work. @SendNukez 

Seems like the only solution is:
- Update graphic card drivers _(works for some people)_
- Disable hardware-acceleration in browser _(works for everyone)_

As this started to become an issue recently, I'll just assume that it is either:
- Graphic card driver issue
- Webkit engine issue  _(unless it's not working in Firefox too)_
- Windows 10 issue

There's a good comment by @Smart123s left early on: [#issuecomment-768489842](https://github.com/dvlden/ultrawideo/issues/46#issuecomment-768489842)

Seems like there's nothing I can do to solve this problem, but wait for one of the possible issues above to solve theirs.

**Comment by Mackeriah** [comment]
Hello.  

Just wanted to post to say that disabling hardware acceleration on Chrome browser (Brave) resolved this immediately for me also.

If further details of my system/browser would be useful, just let me know.

Cheers
Owen

**Comment by tamius-han** [comment]
Another solution, as per [Chromium bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=1199871#c2) comments:

Run Chrome with `--disable-direct-composition-video-overlays`.

That way you _probably_ still keep most of the benefits of hardware acceleration.

**Comment by dvlden** [comment]
@tamius-han Glad that you reported that to them. Thank you for sharing this with everyone!

**Comment by Mackeriah** [comment]
Thanks so much for this @tamius-han.  Fixed my issue too (using Brave browser)

**Comment by knlp** [comment]
> Another solution, as per [Chromium bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=1199871#c2) comments:
> 
> Run Chrome with `--disable-direct-composition-video-overlays`.
> 
> That way you _probably_ still keep most of the benefits of hardware acceleration.

Awesome! Works like a charm in Opera.

**Comment by MrJeems** [comment]
Issue with Chrome.  Extension did nothing until I disabled Hardware Acceleration.  Now that it's disabled:
Normal mode does nothing; still has letterboxes at top and bottom.
Upscale crops the letterbox and seemingly another letterbox worth of valid video from top and bottom.
Stretch definitely stretches and maintains horizontal letterboxes.

Win10.0.19042 Build 19042
Chrome 91.0.4472.114 (64-bit)
RTX2080 Super.
Odyssey G9 @5120x1440

**Comment by markey** [comment]
@MrJeems 
> Issue with Chrome. Extension did nothing until I disabled Hardware Acceleration. Now that it's disabled:
> Normal mode does nothing; still has letterboxes at top and bottom.
> Upscale crops the letterbox and seemingly another letterbox worth of valid video from top and bottom.
> Stretch definitely stretches and maintains horizontal letterboxes.
 
Did you try the workaround mentioned above? It works on Edge right now for me:

> Run Chrome with --disable-direct-composition-video-overlays

**Comment by MrJeems** [comment]
> @MrJeems
> Did you try the workaround mentioned above? It works on Edge right now for me:
> > Run Chrome with --disable-direct-composition-video-overlays
Just tried it with Chrome and it still performs the same way.  Nothing on Normal, crops content as well with Upscale, and ultrawide distortion when stretched.  I have a feeling it's something to do with the Ultra-wide aspect ratio of my monitor.

**Comment by dvlden** [comment]
@MrJeems Please be aware that:

- **Normal** - should not affect your video. It might normalize it, if something is wrong, but its purpose is "Restore back to Normal, without the need to pause the extension"
- **Upscale** - get rid of all black bars (horizontally and vertically) in order to get a video across the entire screen
- **Stretch** - get rid of all black bars, but unlike upscale, it will keep entire video, but distort the image

If your Ultra Wide screen is too wide, this extension won't be good fit for you. I am using 32" UW monitor and I watch everything on Upscale, except video tutorials that contain text/charts or some data like that.
